// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var GrayMatter = require("gray-matter");
var MarkdownIt = require("markdown-it");

var md = new MarkdownIt();

function mdToHtml(mdfile) {
  return md.render(mdfile);
}

function mdToMatter(mdfile) {
  return GrayMatter(mdfile);
}

exports.md = md;
exports.mdToHtml = mdToHtml;
exports.mdToMatter = mdToMatter;
/* md Not a pure module */
