// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("rescript/lib/js/array.js");
var Kleur = require("kleur").default;

function flatten(arr) {
  return $$Array.concat($$Array.to_list(arr));
}

var Klaw = {};

var Kleur$1 = {};

function logMessage(msg) {
  var variant = msg.NAME;
  console.log(variant === "error" ? Kleur.bold(undefined).red("--- Oh no, we found error ---\n>> " + msg.VAL + " <<\n") : (
          variant === "warning" ? Kleur.bold(undefined).yellow("--- Just in case, warning ---\n>> " + msg.VAL + " <<\n") : Kleur.bold(undefined).blue("--- Information for you ---\n>> " + msg.VAL + " <<\n")
        ));
  
}

var ErrorMessage = {
  logMessage: logMessage
};

var Chokidar = {};

var LiveServer = {};

exports.flatten = flatten;
exports.Klaw = Klaw;
exports.Kleur = Kleur$1;
exports.ErrorMessage = ErrorMessage;
exports.Chokidar = Chokidar;
exports.LiveServer = LiveServer;
/* kleur Not a pure module */
