// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Internal__Dust_Syntax$Dust = require("./Internal__Dust_Syntax.js");

var Elements = Internal__Dust_Syntax$Dust.Html.Elements;

var Properties = Internal__Dust_Syntax$Dust.Html.Properties;

exports.Elements = Elements;
exports.Properties = Properties;
/* No side effect */
