// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Internal__Dust_Syntax$DustSsg from "./Syntax/Internal__Dust_Syntax.mjs";

function main(param) {
  return Curry._2(Internal__Dust_Syntax$DustSsg.Html.Elements.html, {
              hd: Curry._1(Internal__Dust_Syntax$DustSsg.Html.Properties.lang, "en"),
              tl: /* [] */0
            }, {
              hd: Curry._2(Internal__Dust_Syntax$DustSsg.Html.Elements.body, /* [] */0, {
                    hd: Curry._2(Internal__Dust_Syntax$DustSsg.Html.Elements.h1, /* [] */0, Curry._1(Internal__Dust_Syntax$DustSsg.Html.Elements.text, "test it out")),
                    tl: {
                      hd: Curry._2(Internal__Dust_Syntax$DustSsg.Html.Elements.a, {
                            hd: Curry._1(Internal__Dust_Syntax$DustSsg.Html.Properties.disabled, true),
                            tl: {
                              hd: Curry._1(Internal__Dust_Syntax$DustSsg.Html.Properties.rel__a, "Nofollow"),
                              tl: /* [] */0
                            }
                          }, Curry._1(Internal__Dust_Syntax$DustSsg.Html.Elements.text, "link bokep")),
                      tl: /* [] */0
                    }
                  }),
              tl: /* [] */0
            });
}

console.log(main(undefined));

var H;

var P;

export {
  H ,
  P ,
  main ,
  
}
/*  Not a pure module */
